FROM python:3.11-slim AS builder

WORKDIR /app

COPY requirements/train.txt .

RUN pip install --no-cache-dir --prefix=/install -r train.txt


FROM python:3.11-slim

WORKDIR /app
LABEL org.opencontainers.image.title="CIFAR-10 Training Pipeline"
COPY --from=builder /install /usr/local

COPY src ./src
COPY configs ./configs

RUN mkdir -p /app/data /app/checkpoints

ENV PYTHONUNBUFFERED=1

CMD ["python", "src/train.py", "--config", "configs/training_config.yaml"]